"""empty message

Revision ID: 12acf66dce77
Revises: a165f07907ce
Create Date: 2019-10-02 14:59:50.520581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12acf66dce77'
down_revision = 'a165f07907ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('syllabus', sa.String(length=2000), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('default_img', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'enrolled', 'module', ['module_id'], ['id'])
    op.create_foreign_key(None, 'image', 'module', ['module_id'], ['id'])
    op.create_foreign_key(None, 'module_review', 'module', ['module_id'], ['id'])
    op.create_foreign_key(None, 'module_series', 'module', ['module_id'], ['id'])
    op.create_foreign_key(None, 'order', 'module', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'module_series', type_='foreignkey')
    op.drop_constraint(None, 'module_review', type_='foreignkey')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_constraint(None, 'enrolled', type_='foreignkey')
    op.drop_table('module')
    # ### end Alembic commands ###
