"""empty message

Revision ID: 670981b1c38d
Revises: 3905613b8d60
Create Date: 2019-09-27 17:28:55.842102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670981b1c38d'
down_revision = '3905613b8d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
