"""empty message

Revision ID: 796d2531a5f7
Revises: e31bd5f0a12b
Create Date: 2019-09-26 16:47:35.687942

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '796d2531a5f7'
down_revision = 'e31bd5f0a12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=True),
                    sa.Column('email', sa.String(length=256), nullable=True),
                    sa.Column('role', sa.String(length=256), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('flask_dance_oauth',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('provider', sa.String(
                        length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('token', sqlalchemy_utils.types.json.JSONType(),
                              nullable=False),
                    sa.Column('provider_user_id', sa.String(
                        length=256), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('provider_user_id')
                    )
    op.create_table('profile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=256), nullable=True),
                    sa.Column('last_name', sa.String(
                        length=256), nullable=True),
                    sa.Column('email', sa.String(length=256), nullable=True),
                    sa.Column('dob', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('token',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sa.String(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('uuid')
                    )
    op.create_foreign_key(None, 'enrolled', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'module', 'users', ['mentor_id'], ['id'])
    op.create_foreign_key(None, 'module_review', 'users',
                          ['student_id'], ['id'])
    op.create_foreign_key(None, 'order', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'module_review', type_='foreignkey')
    op.drop_constraint(None, 'module', type_='foreignkey')
    op.drop_constraint(None, 'enrolled', type_='foreignkey')
    op.drop_table('token')
    op.drop_table('profile')
    op.drop_table('flask_dance_oauth')
    op.drop_table('users')
    # ### end Alembic commands ###
