"""empty message

Revision ID: c5956ec28372
Revises: 185bd88448bc
Create Date: 2019-10-01 11:59:46.973988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5956ec28372'
down_revision = '185bd88448bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module', sa.Column('syllabus', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module', 'syllabus')
    # ### end Alembic commands ###
