"""empty message

Revision ID: cfddac12c7d1
Revises: 796d2531a5f7
Create Date: 2019-09-26 19:49:43.487750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfddac12c7d1'
down_revision = '796d2531a5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('about', sa.String(length=3000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'about')
    # ### end Alembic commands ###
